apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cluster-ingress
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 128Mi